### ISSUE TITLE
No character image is displayed.

### ISSUE THREAD

**Issue by max-dicson-cf** [greenelfx/MapleBit#33]
Hi, I am experiencing this error, I don't know what is really due, but I see that it is responding with status 200. However the character image is not shown. I have followed the installation procedures step by step. I have unzipped the .7z file on my server too.
I hope you can help me, thanks.

![maplestory](https://user-images.githubusercontent.com/5543144/88502893-8532d800-cf95-11ea-8315-c1790bfb5dd6.png)

I also attach the image files from my server:

![server](https://user-images.githubusercontent.com/5543144/88503006-ee1a5000-cf95-11ea-9612-666565564b2b.png)

**Comment by max-dicson-cf** [comment]
MapleStory Versión is: HeavenMS v83

**Comment by greenelfx** [comment]
can you post your server error logs?

**Comment by max-dicson-cf** [comment]
the response http is 200

**Comment by greenelfx** [comment]
can you use a debugger of var_dump to discover what the output of the png is?

**Comment by max-dicson-cf** [comment]
lo intentaré.

**Comment by tuwary** [comment]
I am experiencing this error too.

**Comment by bomberman29** [comment]
Me too
 but try to install maplebit v1.2 the charecter image will work!
