### ISSUE TITLE
Admin Panel/Login

### ISSUE THREAD

**Issue by Robbydisme** [greenelfx/MapleBit#34]
Hey guys. I used to love and always refer to MapleBit whenever I wanted to play around with Maplestory servers. However recently, I seem to have a major issue with getting the admin panel to work at all. I've tried basically every version in the releases, swapping between wamp versions, xampp, and everything I could think of. Basically, I assign my username as an admin, and try to login and the login button does absolutely nothing for me. No errors show up, and everything seems to be functioning fine besides that. No incorrect password, I've tried using passwords in all forms between text, and also trying all of the hash methods. Is there something really stupid I'm overlooking? Any help is appreciated, thanks!

**Comment by greenelfx** [comment]
Can you verify you have a column in your accounts table named `webadmin`, and the value of the column in the row associated with your account is set to `1`?

**Comment by Robbydisme** [comment]
Yes, 
![Screenshot_84](https://user-images.githubusercontent.com/69019852/88985407-2b385800-d29e-11ea-9323-a8fb09627bf0.png)

**Comment by greenelfx** [comment]
So to be clear, the issue is the login panel on the left hand side. Can you look at what the server response is from the login panel? Use your chrome network tools. It may be that your password is not using sha1 (or maplebit is not configured to use sha1)
You can also use echo or vardump to inspect what's going wrong in the login script

**Comment by Robbydisme** [comment]
Ahh now I'm learning things thanks to you!
at least I have an error now... here's what came up not really sure what it means, though. :
![Screenshot_85](https://user-images.githubusercontent.com/69019852/88986677-af400f00-d2a1-11ea-8662-562c63176eed.png)

**Comment by greenelfx** [comment]
Add a column in your accounts table called "salt" of type varchar or text (doesn't matter especially if your source does not use salt). Default can be empty string ""
See if that helps.

**Comment by Robbydisme** [comment]
Okay, Now it's saying incorrect password. I tried using a SHA1 generator online to make a password that works with it, but apparently it's not reading that. If you have immediate access to your own CMS, could you create a random password for me in the form of SHA1 so I could copy/paste to test it? I have no way of getting it if I cant get into control panel to add my recaptcha to register in the first place haha

**Comment by Robbydisme** [comment]
nevermind, apparently the sha1 gene I was using was trash. got another one and was able to log-in. So apparently, the only issue so far was that "salt" was required in the account table for me to login. I'm going to explore some more to see if I find any more issues. My next challenge is to make HeavenMS compatible with this god-tier CMS. Thanks so much for helping!
![Screenshot_86](https://user-images.githubusercontent.com/69019852/88987911-62f6ce00-d2a5-11ea-9e7b-b87178a1e371.png)

**Comment by greenelfx** [comment]
enjoy!
