### ISSUE TITLE
Account recovery options

### ISSUE THREAD

**Issue by Graxo** [greenelfx/MapleBit#39]
**Is your feature request related to a problem? Please describe.**
Account recovery options

**Describe the solution you'd like**
A way for users to recover their password or in-game pincode.

**Describe alternatives you've considered**
I havent any.

**Additional context**

**Comment by Graxo** [comment]
Ping!

**Comment by greenelfx** [comment]
No feature requests at this time, please. Pull requests accepted and encouraged.
