### ISSUE TITLE
SMTP Mailing settings

### ISSUE THREAD

**Issue by Graxo** [greenelfx/MapleBit#40]
**Is your feature request related to a problem? Please describe.**
A way to reach my end-users by email

**Describe the solution you'd like**
I would like to use SMTP to send emails to my end-users.

**Describe alternatives you've considered**
No, i havent.

**Additional context**

**Comment by Graxo** [comment]
Ping!

**Comment by greenelfx** [comment]
No feature requests at this time, please. Pull requests accepted and encouraged.
